## Working with Tensors

The `polycrystal` package has three systems for representing tensor data (matrices): the `Voigt` system, the `Mandel` system and the `SymmDev` system. Each system represents matrices as vectors with nine components. In all three systems, the first six components represent the symmetric part, and the last three represent the skew part (in the same way).  The `SymmDev` system breaks the symmetric part further into two parts--the spherical part and the symmetric deviatoric part. 

In [4]:
import numpy as np

from polycrystal.utils.tensor_data.voigt_system import VoigtSystem
from polycrystal.utils.tensor_data.mandel_system import MandelSystem
from polycrystal.utils.tensor_data.symmdev_system import SymmDevSystem

The interface is similar for all three systems. You can initialize with an array of matrices, or you can build the matrices from their components in the system. For
example, in the `Voigt` system, each matrix has 9 components, with the first
six for the symmetric part (`symm`) and the last three for the skew part (`skew`).

Let's start by generating an array of random matrices.

In [5]:
mats = np.array([
    np.diag([1, 2, 3]),     # diagonal matrix
    2.1 * np.ones((3, 3)),  # all value 2.1
    np.arange(9).reshape((3, 3)) # numbers 0 through 8
])
mats

array([[[1. , 0. , 0. ],
        [0. , 2. , 0. ],
        [0. , 0. , 3. ]],

       [[2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1]],

       [[0. , 1. , 2. ],
        [3. , 4. , 5. ],
        [6. , 7. , 8. ]]])

Using the `Voigt` system, load the matrices and print the components. The array of components has shape (3, 9). The first matrix is diagonal, so only the first three components are nonzero. The second is symmetric, so the first six are nonzero. The third has nonzero symmetric and skew parts, and all nine components are nonzero.

In [6]:
v_mats = VoigtSystem(mats)
v_mats.components

array([[ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 2.1,  2.1,  2.1,  2.1,  2.1,  2.1,  0. ,  0. ,  0. ],
       [ 0. ,  4. ,  8. ,  6. ,  4. ,  2. ,  1. , -2. ,  1. ]])

The symmetric components have shape (3, 6).

In [7]:
v_mats.symm

array([[1. , 2. , 3. , 0. , 0. , 0. ],
       [2.1, 2.1, 2.1, 2.1, 2.1, 2.1],
       [0. , 4. , 8. , 6. , 4. , 2. ]])

Finally, the skew components have shape (3, 3).

In [8]:
v_mats.skew

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1., -2.,  1.]])

You can also reconstruct the full matrix or the individual parts.

In [9]:
v_mats_2 = VoigtSystem.from_parts(symm=v_mats.symm, skew=v_mats.skew)
v_mats_2.matrices

array([[[1. , 0. , 0. ],
        [0. , 2. , 0. ],
        [0. , 0. , 3. ]],

       [[2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1]],

       [[0. , 1. , 2. ],
        [3. , 4. , 5. ],
        [6. , 7. , 8. ]]])

We can build the specific parts. Here we build the symmetric parts, as matrices.

In [10]:
# To build the symmetric parts:
v_mats_symm = VoigtSystem.from_parts(symm=v_mats.symm)
v_mats_symm.matrices

array([[[1. , 0. , 0. ],
        [0. , 2. , 0. ],
        [0. , 0. , 3. ]],

       [[2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1],
        [2.1, 2.1, 2.1]],

       [[0. , 2. , 4. ],
        [2. , 4. , 6. ],
        [4. , 6. , 8. ]]])

And now we build the skew parts, as matrices.

In [11]:
# To build the skew parts:
v_mats_skew = VoigtSystem.from_parts(skew=v_mats.skew)
v_mats_skew.matrices

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0., -1., -2.],
        [ 1.,  0., -1.],
        [ 2.,  1.,  0.]]])

Now let's switch to another system. We will use the `Mandel` system. Simply initialize with the matrices. Then you can take components as in the `Voigt` system. 

In [12]:
# To switch to another system.
m_mats = MandelSystem(v_mats.matrices)

# Now, you can see the components in the Mandel system.
m_mats.components

array([[ 1.    ,  2.    ,  3.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 2.1   ,  2.1   ,  2.1   ,  2.9698,  2.9698,  2.9698,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  4.    ,  8.    ,  8.4853,  5.6569,  2.8284,  1.4142,
        -2.8284,  1.4142]])

We can do the same thing with `SymmDev` system.  

In [15]:
s_mats = SymmDevSystem(v_mats.matrices)
s_mats.components

array([[ 3.4641, -0.7071, -1.4142,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 3.6373,  0.    ,  0.    ,  2.9698,  2.9698,  2.9698,  0.    ,
         0.    ,  0.    ],
       [ 6.9282, -2.8284, -5.6569,  8.4853,  5.6569,  2.8284,  1.4142,
        -2.8284,  1.4142]])

The `SymmDev` system has spherical, symmetric-deviatoric, and skew parts.  You can see the components like this:

In [16]:
print(
    "sph components:\n", s_mats.sph,
    "\n\nsymmdev components:\n", s_mats.symmdev,
    "\n\nskew components:\n", s_mats.skew
)

sph components:
 [3.4641 3.6373 6.9282] 

symmdev components:
 [[-0.7071 -1.4142  0.      0.      0.    ]
 [ 0.      0.      2.9698  2.9698  2.9698]
 [-2.8284 -5.6569  8.4853  5.6569  2.8284]] 

skew components:
 [[ 0.      0.      0.    ]
 [ 0.      0.      0.    ]
 [ 1.4142 -2.8284  1.4142]]
